# Database Configuration
DB_URL=jdbc:mysql://127.0.0.1:3306/intellidetect?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
DB_USERNAME=root
DB_PASSWORD=your_database_password

# Huawei Cloud IoTDA Configuration
IOTDA_REGION_ID=cn-north-4
IOTDA_ENDPOINT=your_iotda_endpoint
IOTDA_ACCESS_KEY=your_access_key
IOTDA_SECRET_KEY=your_secret_key
IOTDA_PROJECT_ID=your_project_id
IOTDA_DEVICE_ID=your_device_id
